import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Suspense fallback={<div>Loading...</div>}>
          <div className="container mx-auto">{children}</div>
        </Suspense>
      </body>
    </html>
  );
}
